'use strict';

Object.defineProperty(exports, "__esModule", {
    value: true
});
/** i18n **/
var CHANGE_LOCALE = exports.CHANGE_LOCALE = 'CHANGE_LOCALE';

/** Login **/
var LOGIN = exports.LOGIN = 'LOGIN';
var LOGIN_SUCCESS = exports.LOGIN_SUCCESS = 'LOGIN_SUCCESS';
var LOGIN_ERROR = exports.LOGIN_ERROR = 'LOGIN_ERROR';

/** Register **/
var CREATE_USER = exports.CREATE_USER = 'CREATE_USER';
var CREATE_USER_ERROR = exports.CREATE_USER_ERROR = 'CREATE_USER_ERROR';

/** Posts **/
var INITIAL_POSTS = exports.INITIAL_POSTS = 'INITIAL_POSTS';
var FETCH_POSTS = exports.FETCH_POSTS = 'FETCH_POSTS';
var FETCH_POSTS_SUCCESS = exports.FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
var FETCH_POSTS_ERROR = exports.FETCH_POSTS_ERROR = 'FETCH_POSTS_ERROR';
var CREATE_POST = exports.CREATE_POST = 'CREATE_POST';
var CREATE_POST_ERROR = exports.CREATE_POST_ERROR = 'CREATE_POST_ERROR';
var FETCH_POST = exports.FETCH_POST = 'FETCH_POST';
var FETCH_POST_SUCCESS = exports.FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
var FETCH_POST_ERROR = exports.FETCH_POST_ERROR = 'FETCH_POST_ERROR';
var DELETE_POST = exports.DELETE_POST = 'DELETE_POST';
var DELETE_POST_ERROR = exports.DELETE_POST_ERROR = 'DELETE_POST_ERROR';

